// Generated by CoffeeScript 1.6.3
(function() {
  var adOptOut, confirm, createCookie, readCookie, switchTheme;

  (function(xhr) {
    var open;
    open = XMLHttpRequest.prototype.open;
    return xhr.prototype.open = function() {
      open.apply(this, arguments);
      return this.setRequestHeader('X-Requested-With', 'XMLHttpRequest');
    };
  })(XMLHttpRequest);

  Array.prototype.remove = function(from, to) {
    var rest, _ref;
    rest = this.slice((to || from) + 1 || this.length);
    this.length = (_ref = from < 0) != null ? _ref : this.length + {
      from: from
    };
    return this.push.apply(this, rest);
  };

  Array.prototype.contains = function(a) {
    var i, _i, _ref;
    for (i = _i = 0, _ref = this.length; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
      if (this[i] === a) {
        return true;
      }
    }
    return false;
  };

  readCookie = function(name) {
    var c, ca, nameEQ, _i, _len;
    nameEQ = name + "=";
    ca = document.cookie.split(';');
    for (_i = 0, _len = ca.length; _i < _len; _i++) {
      c = ca[_i];
      while (c.charAt(0) === ' ') {
        c = c.substring(1, c.length);
      }
      if (c.indexOf(nameEQ) === 0) {
        return c.substring(nameEQ.length, c.length);
      }
    }
    return null;
  };

  window.readCookie = readCookie;

  createCookie = function(name, value, days) {
    var date, expires;
    if (days) {
      date = new Date();
      date.setTime(date.getTime() + (days * 24 * 60 * 60 * 1000));
      expires = "; expires=" + date.toGMTString();
    } else {
      expires = "; expires=Thu, 01-Jan-1970 00:00:01 GMT";
    }
    return document.cookie = name + "=" + value + expires + "; path=/";
  };

  window.createCookie = createCookie;

  adOptOut = function(showAlert) {
    var gad, lgad;
    createCookie('ad-opt-out', 1, 3650);
    gad = document.getElementById('gad');
    lgad = document.getElementById('lgad');
    if (gad) {
      gad.innerHTML = "You won't see any ads again. If you regret it, head over to the <a href='/donate'>donation</a> page, where you can opt-in.";
    }
    if (lgad) {
      lgad.innerHTML = "You won't see any ads again. If you regret it, head over to the <a href='/donate'>donation</a> page, where you can opt-in.";
    }
    if (showAlert) {
      return alert("You won't see any ads again. If you regret it, head over to the donation page, where you can opt-in.");
    }
  };

  window.adOptOut = adOptOut;

  switchTheme = function() {
    if (readCookie('dark_theme')) {
      createCookie('dark_theme', '', -1);
    } else {
      createCookie('dark_theme', 1, 3650);
    }
    return window.location.href = window.location.href;
  };

  window.switchTheme = switchTheme;

  window.addEventListener('load', function() {
    var dialogNo, dialogYes, feedback, feedbackSend, feedbackToggle;
    feedback = document.getElementById('feedback').querySelector('div');
    feedbackToggle = document.getElementById('toggle-feedback');
    if (foobar) {
      feedbackToggle.addEventListener('click', function(e) {
        e.preventDefault();
        if (feedbackToggle.parentElement.className.indexOf('active') === -1) {
          feedbackToggle.parentElement.classList.add('active');
          return feedback.querySelector('textarea').focus();
        } else {
          return feedbackToggle.parentElement.classList.remove('active');
        }
      }, false);
    }
    feedbackSend = document.getElementById('send-feedback');
    if (feedbackSend) {
      feedbackSend.addEventListener('click', function(e) {
        var feedbackText, formData, xhr;
        e.preventDefault();
        feedbackText = document.getElementById('feedback-text');
        xhr = new XMLHttpRequest();
        formData = new FormData();
        xhr.open('POST', '/api/feedback');
        formData.append('feedback', feedbackText.value);
        xhr.onload = function() {
          var result;
          result = (function() {
            switch (this.status) {
              case 200:
                return "Thanks! We read every one of these. Keep in mind, though, this feedback is anonymous. <a href='mailto:support@mediacru.sh'>Email us</a> if you want a response.";
              case 420:
                return "Sorry, you can't send more feedback today. Try again in 24 hours!";
              case 413:
                return "Sorry, that feedback is too long.";
              default:
                return "Sorry, something unexpected happened.";
            }
          }).call(this);
          return feedback.innerHTML = "<p>" + result + "</p>";
        };
        return xhr.send(formData);
      }, false);
    }
    dialogYes = document.querySelector('.dialog .yes');
    dialogNo = document.querySelector('.dialog .no');
    dialogYes.addEventListener('click', function(e) {
      var confirmCallback;
      e.preventDefault();
      if (confirmCallback) {
        confirmCallback(true);
      }
      confirmCallback = null;
      return document.querySelector('.dialog').classList.add('hidden');
    }, false);
    return dialogNo.addEventListener('click', function(e) {
      var confirmCallback;
      e.preventDefault();
      if (confirmCallback) {
        confirmCallback(false);
      }
      confirmCallback = null;
      return document.querySelector('.dialog').classList.add('hidden');
    }, false);
  }, false);

  confirm = function(callback) {
    var confirmCallback;
    confirmCallback = callback;
    return document.querySelector('.dialog').classList.remove('hidden');
  };

  window.confirm = confirm;

}).call(this);
