// Generated by CoffeeScript 1.6.3
(function() {
  var dragNop, handleDragEnter;

  window.addEventListener('load', function() {
    window.addEventListener('dragenter', handleDragEnter, false);
    window.addEventListener('dragleave', handleDragLeave, false);
    window.addEventListener('dragover', handleDragOver, false);
    return window.addEventListener('drop', handleDragDrop, false);
  }, false);

  window.onbeforeunload = function() {
    if (false) {
      return 'If you leave this page, your uploads will be cancelled.';
    }
  };

  dragNop = function(e) {
    e.stopPropegation();
    return e.preventDefault();
  };

  handleDragEnter = function(e) {
    dragNop(e);
    return document.getElementById('droparea').classList.add('hover');
  };

}).call(this);
