Thingiloader=function(c){this.load_binary_resource=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.overrideMimeType("text/plain; charset=x-user-defined");b.send(null);return 200!=b.status?"":b.responseText};this.loadSTL=function(a){workerFacadeMessage({status:"message",content:"Downloading "+a});a=this.load_binary_resource(a);var b=new BinaryReader(a);b.seek(80);var g=84+50*b.readUInt32();b.getSize()==g?this.loadSTLBinary(b):this.loadSTLString(a)};this.loadOBJ=function(a){workerFacadeMessage({status:"message",
content:"Downloading "+a});a=this.load_binary_resource(a);this.loadOBJString(a)};this.loadJSON=function(a){workerFacadeMessage({status:"message",content:"Downloading "+a});a=this.load_binary_resource(a);this.loadJSONString(a)};this.loadPLY=function(a){workerFacadeMessage({status:"message",content:"Downloading "+a});a=this.load_binary_resource(a);a.match(/format ascii/i)?this.loadPLYString(a):this.loadPLYBinary(a)};this.loadSTLString=function(a){workerFacadeMessage({status:"message",content:"Parsing STL String..."});
workerFacadeMessage({status:"complete",content:this.ParseSTLString(a)})};this.loadSTLBinary=function(a){workerFacadeMessage({status:"message",content:"Parsing STL Binary..."});workerFacadeMessage({status:"complete",content:this.ParseSTLBinary(a)})};this.loadOBJString=function(a){workerFacadeMessage({status:"message",content:"Parsing OBJ String..."});workerFacadeMessage({status:"complete",content:this.ParseOBJString(a)})};this.loadJSONString=function(a){workerFacadeMessage({status:"message",content:"Parsing JSON String..."});
workerFacadeMessage({status:"complete",content:eval(a)})};this.loadPLYString=function(a){workerFacadeMessage({status:"message",content:"Parsing PLY String..."});workerFacadeMessage({status:"complete_points",content:this.ParsePLYString(a)})};this.loadPLYBinary=function(a){workerFacadeMessage({status:"message",content:"Parsing PLY Binary..."});workerFacadeMessage({status:"complete_points",content:this.ParsePLYBinary(a)})};this.ParsePLYString=function(a){var b=[],g=[],d=[],c=/ply\n([\s\S]+)\nend_header/ig.exec(a)[1];
a=/end_header\n([\s\S]+)$/ig.exec(a)[1];header_parts=c.split("\n");for(i in header_parts)/element vertex/i.test(header_parts[i])?/element vertex (\d+)/i.exec(header_parts[i]):/property/i.test(header_parts[i])&&b.push(/property (.*) (.*)/i.exec(header_parts[i])[2]);data_parts=a.split("\n");for(i in data_parts)data_line=data_parts[i],data_line_parts=data_line.split(" "),g.push([parseFloat(data_line_parts[b.indexOf("x")]),parseFloat(data_line_parts[b.indexOf("y")]),parseFloat(data_line_parts[b.indexOf("z")])]),
d.push([parseInt(data_line_parts[b.indexOf("red")]),parseInt(data_line_parts[b.indexOf("green")]),parseInt(data_line_parts[b.indexOf("blue")])]);return[g,d]};this.ParsePLYBinary=function(a){return!1};this.ParseSTLBinary=function(a){a.seek(80);for(var b=a.readUInt32(),g=[],d={},c=[],e=0;e<b;e++){0==e%100&&(workerFacadeMessage({status:"message",content:"Parsing "+(e+1)+" of "+b+" polygons..."}),workerFacadeMessage({status:"progress",content:parseInt(e/b*100)+"%"}));a.seek(a.getPosition()+12);for(var m=
[],h=0;3>h;h++){var k=[a.readFloat(),a.readFloat(),a.readFloat()],f=d[k];null==f&&(f=g.length,g.push(k),d[k]=f);m.push(f)}c.push(m);a.readUInt16()}return[g,c]};this.ParseSTLString=function(a){var b=[],c=[],d={};a=a.replace(/\r/,"\n");a=a.replace(/^solid[^\n]*/,"");a=a.replace(/\n/g," ");a=a.replace(/facet normal /g,"");a=a.replace(/outer loop/g,"");a=a.replace(/vertex /g,"");a=a.replace(/endloop/g,"");a=a.replace(/endfacet/g,"");a=a.replace(/endsolid[^\n]*/,"");a=a.replace(/\s+/g," ");a=a.replace(/^\s+/,
"");var l=0;a=a.split(" ");workerFacadeMessage({status:"message",content:"Parsing vertices..."});for(var e=0;e<a.length/12-1;e++){0==e%100&&workerFacadeMessage({status:"progress",content:parseInt(e/(a.length/12-1)*100)+"%"});for(var m=[],h=0;3>h;h++){var k=[parseFloat(a[l+3*h+3]),parseFloat(a[l+3*h+4]),parseFloat(a[l+3*h+5])],f=d[k];null==f&&(f=b.length,b.push(k),d[k]=f);m.push(f)}c.push(m);l+=12}return[b,c]};this.ParseOBJString=function(a){var b=[],c=[];a=a.split("\n");for(var d=0;d<a.length;d++)workerFacadeMessage({status:"progress",
content:parseInt(d/a.length*100)+"%"}),line_parts=a[d].replace(/\s+/g," ").split(" "),"v"==line_parts[0]?b.push([parseFloat(line_parts[1]),parseFloat(line_parts[2]),parseFloat(line_parts[3])]):"f"==line_parts[0]&&c.push([parseFloat(line_parts[1].split("/")[0])-1,parseFloat(line_parts[2].split("/")[0])-1,parseFloat(line_parts[3].split("/")[0]-1),0]);return[b,c]};switch(c.data.cmd){case "loadSTL":this.loadSTL(c.data.param);break;case "loadSTLString":this.loadSTLString(c.data.param);break;case "loadSTLBinary":this.loadSTLBinary(c.data.param);
break;case "loadOBJ":this.loadOBJ(c.data.param);break;case "loadOBJString":this.loadOBJString(c.data.param);break;case "loadJSON":this.loadJSON(c.data.param);break;case "loadPLY":this.loadPLY(c.data.param);break;case "loadPLYString":this.loadPLYString(c.data.param);break;case "loadPLYBinary":this.loadPLYBinary(c.data.param)}};
"undefined"===typeof window?(onmessage=Thingiloader,workerFacadeMessage=postMessage,importScripts("binaryReader.js")):workerFacadeMessage=WorkerFacade.add(thingiurlbase+"/thingiloader.js",Thingiloader);
